name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'
        modules: 'qtcharts qtquickcontrols2'

    - name: Build
      shell: cmd
      run: |
        qmake -v
        qmake Blippy.pro
        mingw32-make -j4

    - name: Deploy Qt
      shell: cmd
      run: |
        windeployqt --release release\Blippy.exe

    - name: Create Installer with Inno Setup
      shell: cmd
      run: |
        choco install innosetup -y
        iscc installer\blippy.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Blippy-Setup
        path: release\Blippy-Setup-*.exe
        if-no-files-found: error
