name: Windows Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-qt-6.5.0-mingw

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        modules: 'qtdeclarative qtquickcontrols2 qtsvg'

    - name: Build
      shell: cmd
      run: |
        qmake Blippy.pro
        mingw32-make -j2

    - name: Deploy
      shell: cmd
      run: |
        windeployqt --release release\Blippy.exe

    - name: Create Installer
      shell: cmd
      run: |
        choco install innosetup -y --no-progress
        iscc installer\blippy.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Blippy-Installer
        path: release/Blippy-Setup-*.exe
